Add custom repo functionality
ansible-collections/osbuild.composer pull request #36
Opened 2022-11-10 21:45 UTC by matoval

##### SUMMARY

Add custom repo functionality

Add ability to add custom repos as a new source for custom packages

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2022-11-10 23:48 UTC, maxamillion commented
I would propose that we rename `plugins/modules/add_source.py` to `plugins/modules/repository.py` and add a parameter called `state` that allows either `present` or `absent` similar to the `package`/`yum`/`dnf` modules, then add the logic to handle creation, deletion, and change detection for the repository.

2022-11-10 23:49 UTC, maxamillion requested changes
I would propose that we rename `plugins/modules/add_source.py` to `plugins/modules/repository.py` and add a parameter called state that allows either present or absent similar to the `package`/`yum`/`dnf` modules, then add the logic to handle creation, deletion, and change detection for the repository.

2022-11-11 00:53 UTC, chadmf requested changes
Code works, however it needs to be added to the README.md on how to use this functionality.

2022-11-11 00:53 UTC, chadmf commented on roles/setup_server/tasks/main.yaml
> +
Fixed with last push thanks!

2022-11-11 14:58 UTC, maxamillion approved these changes

2022-11-11 14:59 UTC, maxamillion requested changes
Needs integration tests

2022-11-11 18:47 UTC, chadmf commented
LGTM!

2022-11-11 22:37 UTC, maxamillion commented
merging early because it's passed integration tests during our debug session on matrix and I need to make a PR with a lot of changes to make ansible-lint happy

2022-11-11 22:38 UTC, merged